apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: url-shortener-persistent-volume-claim
  namespace: dev

spec:
  resources:
    requests: 
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: url-shortener-persistent-volume
