apiVersion: apps/v1
kind: Deployment

metadata:
  name: url-shortener-postgresql
  namespace: dev

spec:
  replicas: 1
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50
  selector:
    matchLabels:
      postgresql: url-shortener-postgresql
  template:
    metadata:
      labels:
        postgresql: url-shortener-postgresql
    spec:
      containers:
        - name: url-shortener-postgresql
          image: postgres:17.2
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 5432
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 600m
              memory: 800Mi
  