apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: url-shortener-postgresql
  namespace: dev

spec:
  serviceName: postgres-data
  replicas: 1

  selector:
    matchLabels:
      postgresql: url-shortener-postgresql

  template:
    metadata:
      labels:
        postgresql: url-shortener-postgresql

    spec:
      containers:
        - name: url-shortener-postgresql
          image: postgres:17.2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: postgres-secret

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 2Gi

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          startupProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres"]
            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
